SELECT
  *
FROM
  "PATIENT"."READMISSION"."CASE"
LIMIT
  10;
SELECT
    PATIENT_ID,
    AGE,
    GENDER,
    ADMISSION_TYPE,
    LENGTH_OF_STAY,
    NUMBER_OF_DIAGNOSES,
    BLOOD_PRESSURE,
    BLOOD_SUGAR_LEVELS,
    PREVIOUS_ADMISSIONS,
    READMISSION,

    /* READMISSION FLAG */
    CASE WHEN READMISSION = 'YES' THEN 1 ELSE 0 END AS READMISSION_FLAG,

    /* AGE GROUPS */
    CASE
        WHEN AGE < 40 THEN '<40'
        WHEN AGE BETWEEN 40 AND 60 THEN '40-60'
        ELSE '>60'
    END AS AGE_GROUP,

    /* LENGTH OF STAY GROUP */
    CASE
        WHEN LENGTH_OF_STAY <= 5 THEN 'SHORT STAY'
        WHEN LENGTH_OF_STAY BETWEEN 6 AND 10 THEN 'MEDIUM STAY'
        ELSE 'LONG STAY'
    END AS STAY_GROUP,

    /* OVERALL READMISSION RATE */
    AVG(CASE WHEN READMISSION = 'YES' THEN 1 ELSE 0 END) 
        OVER() AS OVERALL_READMISSION_RATE,

    /* Readmission rate by gender */
    AVG(CASE WHEN READMISSION = 'YES' THEN 1 ELSE 0 END) 
        OVER (PARTITION BY GENDER) AS READMISSION_RATE_BY_GENDER,

    /* Readmission rate by admission type */
    AVG(CASE WHEN READMISSION = 'YES' THEN 1 ELSE 0 END) 
        OVER (PARTITION BY ADMISSION_TYPE) AS READMISSION_RATE_BY_ADMISSION,

    /* Readmission rate by age group */
    AVG(CASE WHEN READMISSION = 'YES' THEN 1 ELSE 0 END) 
        OVER (
            PARTITION BY
                CASE
                    WHEN AGE < 40 THEN 1
                    WHEN AGE BETWEEN 40 AND 60 THEN 2
                    ELSE 3
                END
        ) AS READMISSION_RATE_BY_AGE_GROUP 


FROM
    PATIENT.READMISSION."CASE";
    
